#pragma once
#ifndef __HALAK_KEYS_H__
#define __HALAK_KEYS_H__

#   define DIRECTINPUT_VERSION 0x0800
#   include <dinput.h>

    namespace Halak
    {
        struct Keys
        {
            enum E
            {
                None = 0,
                Back = DIK_BACK,
                Tab = DIK_TAB,
                Enter = DIK_RETURN,
                Pause = DIK_PAUSE,
                CapsLock = DIK_CAPSLOCK,
                Escape = DIK_ESCAPE,
                Space = DIK_SPACE,
                PageUp = DIK_PRIOR,
                PageDown = DIK_NEXT,
                End = DIK_END,
                Home = DIK_HOME,
                Left = DIK_LEFT,
                Up = DIK_UP,
                Right = DIK_RIGHT,
                Down = DIK_DOWN,
                PrintScreen = DIK_SYSRQ,
                Insert = DIK_INSERT,
                Delete = DIK_DELETE,
                D0 = DIK_0,
                D1 = DIK_1,
                D2 = DIK_2,
                D3 = DIK_3,
                D4 = DIK_4,
                D5 = DIK_5,
                D6 = DIK_6,
                D7 = DIK_7,
                D8 = DIK_8,
                D9 = DIK_9,
                A = DIK_A,
                B = DIK_B,
                C = DIK_C,
                D = DIK_D,
                E = DIK_E,
                F = DIK_F,
                G = DIK_G,
                H = DIK_H,
                I = DIK_I,
                J = DIK_J,
                K = DIK_K,
                L = DIK_L,
                M = DIK_M,
                N = DIK_N,
                O = DIK_O,
                P = DIK_P,
                Q = DIK_Q,
                R = DIK_R,
                S = DIK_S,
                T = DIK_T,
                U = DIK_U,
                V = DIK_V,
                W = DIK_W,
                X = DIK_X,
                Y = DIK_Y,
                Z = DIK_Z,
                LeftWindows = DIK_LWIN,
                RightWindows = DIK_RWIN,
                NumPad0 = DIK_NUMPAD0,
                NumPad1 = DIK_NUMPAD1,
                NumPad2 = DIK_NUMPAD2,
                NumPad3 = DIK_NUMPAD3,
                NumPad4 = DIK_NUMPAD4,
                NumPad5 = DIK_NUMPAD5,
                NumPad6 = DIK_NUMPAD6,
                NumPad7 = DIK_NUMPAD7,
                NumPad8 = DIK_NUMPAD8,
                NumPad9 = DIK_NUMPAD9,
                Multiply = DIK_MULTIPLY,
                Add = DIK_ADD,
                Subtract = DIK_SUBTRACT,
                Decimal = DIK_DECIMAL,
                Divide = DIK_DIVIDE,
                F1 = DIK_F1,
                F2 = DIK_F2,
                F3 = DIK_F3,
                F4 = DIK_F4,
                F5 = DIK_F5,
                F6 = DIK_F6,
                F7 = DIK_F7,
                F8 = DIK_F8,
                F9 = DIK_F9,
                F10 = DIK_F10,
                F11 = DIK_F11,
                F12 = DIK_F12,
                NumLock = DIK_NUMLOCK,
                Scroll = DIK_SCROLL,
                LeftShift = DIK_LSHIFT,
                RightShift = DIK_RSHIFT,
                LeftControl = DIK_LCONTROL,
                RightControl = DIK_RCONTROL,
                LeftAlt = DIK_LMENU,
                RightAlt = DIK_RMENU,
            };
        };
    }

#endif